### ISSUE TITLE
Project status and release

### ISSUE THREAD

**Issue by gastaldi** [iNamik/java_text_tables#10]
Is this project dead? Otherwise can we have a release in Maven central?

**Comment by davidpfarrell** [comment]
Greetings @gastaldi !

> Is this project dead

Fortunately, no, although I haven't had any epiphanies on how I might want to move the project forward, feature-wise.

> can we have a release in Maven central?

So I did make a release as per our previous discussion in #2 which resulted in this:
* https://mvnrepository.com/artifact/com.github.inamik.text.tables/inamik-text-tables/0.8

Are you having issues related to that specific release?

PS: As a side note, I'd love to hear more about how you're using the project and what features you think might be useful additions?

**Comment by gastaldi** [comment]
Ah I thought that library was the archived version. Closing this issue now ;)

I'm thinking of using it in a CLI app to format the output
