### ISSUE TITLE
Release a 1.0 version in central

### ISSUE THREAD

**Issue by gastaldi** [iNamik/java_text_tables#2]
It would be nice to have a 1.0 version in Maven's central repository. 
Here are the steps to make that happen: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by gastaldi** [comment]
Any forecast of when that could happen?

**Comment by iNamik** [comment]
Thanks for the reminder. I'll try to make some time soon to get on this.

NOTE: I do have a `mvn-repo` branch (although I may need to confirm its configured appropriately)

Also, thinking we would likely have a 1.0-SNAPSHOT (vs 1.0) for awhile.

I'm still trying to reconcile the awkwardness I feel around the existing fill-char support, as well as the idea that width, height and alignment might deserve to be proper citizens of the table (vs apply functions).

-David

**Comment by gastaldi** [comment]
Perhaps a good strategy is using Semantic versioning - http://semver.org (eg. 1.0.0.Alpha1)

**Comment by gsmachado** [comment]
Any news about a release in Maven's central repo? :-)

Also, thumbs up for http://semver.org versioning style. 👍

**Comment by iNamik** [comment]
Greetings !

Per previous comments, I'm not ready to tag a release build, but I did get a snapshot build up !  You can add it to your maven projects via:

```
<repositories>
  <repository>
    <id>oss-sonatype</id>
    <name>oss-sonatype</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.inamik.text.tables</groupId>
    <artifactId>inamik-text-tables</artifactId>
    <version>1.0-SNAPSHOT</version>
  </dependency>
</dependencies>
```

Give it a try and let me know if you run into any problems.

I'll keep this ticket open awhile longer to get some feedback.

Thank you for your interest in my project,

-David

**Comment by gastaldi** [comment]
Another idea is to use Jitpack: https://jitpack.io/

**Comment by vertex-github** [comment]
We cant access snapshot artifacts at some client sites and we want to use this great lib - please push a 1.0 release into maven central so that we can use it!

**Comment by gastaldi** [comment]
Any news on a 1.0 release?

**Comment by steveash** [comment]
I had to release a version of this to maven central for some projects of mine. Sorry. I really don't like to do that because if you ever do release an official version, our group ids will become confusing. But its been almost a year. I cannot wait any longer.

For anyone else following this you can use these coordinates for now:
```xml
<groupId>com.github.steveash.itxttbl</groupId>
<artifactId>inamik-text-tables</artifactId>
<version>0.1</version>
```

**Comment by gastaldi** [comment]
@iNamik can you perform a 1.0 release of this project? Can I help somehow?

**Comment by iNamik** [comment]
Greetings!

I know the delay on a 1.0 release has been frustrating and I apologize.

I'm really not happy enough with the API to consider this a proper 1.0 release.

Maybe I could just call it  `v0.9` or somesuch which would get me past my `1.0` concerns.

**Comment by gastaldi** [comment]
Sure, that works for me

**Comment by iNamik** [comment]
OK looks like I might have actually done it.  I went with `v0.8`

```
<dependency>
    <groupId>com.github.inamik.text.tables</groupId>
    <artifactId>inamik-text-tables</artifactId>
    <version>0.8</version>
</dependency>
```
Let me know if you have any issues with it.

Thanks!

**Comment by gastaldi** [comment]
Works great. Closing issue. Thanks!
