### ISSUE TITLE
Add more options for writing tables out

### ISSUE THREAD

**Issue by steveash** [iNamik/java_text_tables#4]
I would like to have a Util.print method that takes a Writer or PrintWriter.  Also a simple way just to render a String seems reasonable.

**Comment by iNamik** [comment]
Greetings!

I've replaced the `PrintStream` in the main output method with `PrintWriter` and added a few helper methods to adapt `Writer`, and `OutputStream`.  I've also added `asString` which utilizes a `StringWriter` to render a String.

Please have a look and let me know your thoughts.

Thank you for your interest in my project !
